### PR TITLE
Remount container

### PR DESCRIPTION
**Pull request by xop5**

### CODE REVIEW

**Review by ryanraaschCDC — APPROVED** [review]

**Review by ryanraaschCDC — CHANGES_REQUESTED** [review]
we should allow pool_name to be optional since we can pull in the pool name via self.pool_name. I'm also unsure why the autoscale_formula_path parameter is included here for updating the blob containers connected to the pool

**Comment by ryanraaschCDC** [comment]
@xop5 have you tested the new ubuntu version? I tried using the ubuntu hpc container before with no luck since it didn't like the VM when it came time to create nodes. 
I'm thinking we should remove this update from this PR since EDAV will be looking into the ubuntu upgrade

**Comment by xop5** [comment]
Virtua Machine Configuration was committed to this branch by mistake. 
I have reverted these changes because these have yet to be tested.

**Comment by ryanraaschCDC** [comment]
I tried testing the code with the pool autoscale_pool_test (0 active nodes) and got the following error:
image

**Comment by ryanraaschCDC** [comment]
I got this error when running update_containers on the pool autoscale_pool_test. It looks like it's still referencing the batch_json
image

**Pull request merged**
