### PR TITLE
Update container collection

### PR DESCRIPTION
**Pull request by xop5**

### CODE REVIEW

**Comment by ryanraaschCDC** [comment]
We need to revert back to the old ubuntu image rather than use the new HPC image. I didn't have luck with the new HPC image when I tested it out.
Also, it looks like JobConstrainsts was removed from the import in helpers, which is needed for the task retries.

**Comment by xop5** [comment]
Virtual Machine Configuration was committed to this branch by mistake.
I have reverted these changes because these have yet to be tested.
Since we are importing azure.batch.models as batchmodels, I am using JobConstraints as batchmodels.JobConstraints.

**Comment by ryanraaschCDC** [comment]
I'm getting a new error since we don't store the container image name in the config but we're pulling that information in for this function. That information can probably be pulled directly from the pool we want to modify
image

**Comment by ryanraaschCDC** [comment]
When running update_container(), I'm getting the following error since container_registry_url is not currently stored in the config. Check out the example config for what we expect users to have in their config. Also, the helper function get_batch_pool_json is not up to date with get_pool_parameters, which has a lot more flexibility in creating the json for the pool. I would recommend switching to use get_pool_parameters instead.
image

I'm getting the same error as above regarding container image name when I run the update_container_set() function. Make sure we're only looking for info from the config that we have in our example config.

The doc string for update_container_set also needs to be updated since it refers to input and output like in the other update function. It should explain the list of mounts instead.

**Comment by ryanraaschCDC** [comment]
I'm also getting the error that was present on the other branch when running update_container_set:
image

**Pull request merged**
